# Generated by Django 3.0.4 on 2021-05-12 23:11

import core.erp.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, validators=[core.erp.validators.validarLetras], verbose_name='Nombres')),
                ('descripcion', models.CharField(max_length=2000, unique=True, verbose_name='Descripcion')),
                ('link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Link')),
                ('image', models.ImageField(blank=True, upload_to='advertising/%Y/%m/%d', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Live',
                'verbose_name_plural': 'Lives',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='galery/%Y/%m/%d')),
                ('description', models.TextField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Titulo')),
                ('price', models.IntegerField(default=1, null=True, validators=[core.erp.validators.validacionCantidad])),
                ('image', models.ImageField(blank=True, upload_to='image/%Y/%m/%d', verbose_name='Imagen')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='music/%Y/%m/%d', verbose_name='Música')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Musica',
                'verbose_name_plural': 'Musica',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Live',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Titulo')),
                ('link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Link')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Live',
                'verbose_name_plural': 'Lives',
                'ordering': ['id'],
            },
        ),
    ]
